name: Ruby Gem

on:
  push:
    branches: [ "main" ]
    paths:
      - '*.gemspec'
env:
  GIT_BRANCH: main

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby

      - uses: rubygems/release-gem@v1
