name: Ruby Gem

on:
  push:
    branches: [ "main" ]
    paths:
      - '*.gemspec'

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '3.4'
      - uses: rubygems/release-gem@e9a6361a0b14562539327c2a02373edc56dd3169
