name: Ruby

on:
  push:
    paths:
      - 'lib/**'
      - 'spec/**'
  pull_request:
    paths:
      - 'lib/**'
      - 'spec/**'

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.3.6', '3.4.2']

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Install MeCab
      run: sudo apt-get update -qq && sudo apt-get install -y mecab mecab-ipadic-utf8 libmecab-dev sudo

    - name: Install mecab-ipadic-NEologd
      run: git clone --depth 1 https://github.com/neologd/mecab-ipadic-neologd.git && cd mecab-ipadic-neologd && ./bin/install-mecab-ipadic-neologd -n -y

    - name: Uninstall unnecessary library
      run: sudo apt-get remove sudo

    - name: Run tests
      run: bundle exec rspec
      env:
        DICTIONARY_DIR: '/usr/lib/x86_64-linux-gnu/mecab/dic/mecab-ipadic-neologd'
